### ISSUE TITLE
To be done

### ISSUE THREAD

**Issue by tyranron** [kahlan/docker-image#1]
### Roadmap
- [x] `Dockerfile`s generation from template
- [x] ~~install `phpdbg` in `php5` containers~~ (no sense, see [why](https://github.com/kahlan/docker-image/issues/1#issuecomment-256260083))
- [x] install `Xdebug`
- [x] tests included into build process (to check that containers are build as expected)
- [x] create `README.md`
- [x] automated builds from `master` branch
- [x] license
- [x] `HOWTO.md` for maintainers

**Comment by tyranron** [comment]
Tried to run `kahlan` under `phpdbg` for PHP5. It failed with error:

```
$ docker run --rm -it -v $(pwd):/app --entrypoint /usr/local/bin/kahlan-phpdbg kahlan/kahlan:2.5.8-php5-alpine --config=.tests/kahlan-config.php
[Attempting compilation of /usr/src/kahlan/vendor/kahlan/kahlan/bin/kahlan]
[Success]
#!/usr/bin/env php
            _     _
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The Unit/BDD PHP Test Framework for Freedom, Truth, and Justice.

Working Directory: /app

[PHP Fatal error:  Call to undefined function Kahlan\Reporter\Coverage\Driver\phpdbg_start_oplog() in /app/vendor/kahlan/kahlan/src/Reporter/Coverage/Driver/Phpdbg.php on line 37]
 00036:     {
>00037:         phpdbg_start_oplog();
 00038:     }
 00039: 
```

For `php5` official docker image is used `phpdbg` of version `v0.4.0`.

```
/app # phpdbg
[Welcome to phpdbg, the interactive PHP debugger, v0.4.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://github.com/krakjoe/phpdbg/issues>]
```

Which is turned off by default, but can be enabled with from-sources recompiling:

``` Dockerfile
# Example for Alpine based php image
RUN apk add --update --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        curl-dev \
        libedit-dev \
        libxml2-dev \
        openssl-dev \
        sqlite-dev \
 && docker-php-source extract \

 && cd /usr/src/php \
 && ./configure --enable-phpdbg \
 && make -j "$(getconf _NPROCESSORS_ONLN)" \
 && make install-phpdbg \

 && docker-php-source delete \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/*
```

However it has no sense as `v0.4.0` for PHP5 does not support `phpdbg_start_oplog()` function required for code coverage. And won't. See [related topic](https://github.com/krakjoe/phpdbg/issues/150) why.

### Conclusions

Sad =( There will be no `phpdbg` in `php5` Kahlan Docker image versions.

**Comment by tyranron** [comment]
@jails would you be so kind to provide email address of CrysaLEAD to specify it in `MAINTAINER` of this image?

**Comment by jails** [comment]
I added you as a maintainer here https://hub.docker.com/u/kahlan/, is it enough ?
And what about not supporting PHP < 7 ? http://php.net/supported-versions.php ?

**Comment by tyranron** [comment]
@jails thanks, that was also required (I wanted to ask you later). But at the moment I mean [`MAINTAINER` instruction](https://docs.docker.com/engine/reference/builder/#/maintainer) of `Dockerfile`. I think it is right to specify there the same author that owns Kahlan license and is used as author in `composer.json`. It's `CrysaLEAD` at the moment. But for specifying it also requires some email address, not only name. That is what I'm asking you to provide.

I have almost all project still at PHP5. There are a lot of legacy stuff and I'm pretty sure that I'm not alone with that problem. So this is quite necessary.
But I don't invent stuff and only `5.6.*` branch of PHP5  is supported, as [official PHP image](https://hub.docker.com/_/php/) and [Composer image](https://hub.docker.com/r/composer/composer/) do. Our image is just build on top of them.

**Comment by tyranron** [comment]
I'll write `README.md` soon, so things will be more clear.

**Comment by jails** [comment]
Oh ok just use: `contact@crysalead.com`

**Comment by tyranron** [comment]
@jails would you be so kind to check my access privileges to [kahlan/kahlan repo on Dockerhub](https://hub.docker.com/r/kahlan/kahlan/) once again? I was able to `docker push` images there, but from web interface I'm unable to do anything: neither change description, nor add Github link.

**Comment by jails** [comment]
I'm not really familiar with the dockhub permissions thingy. I created a `maintainer` team at the `kahlan` level (i.e orga), added [this user)(https://hub.docker.com/u/tyranron/) in the maintainer team and then added `maintainer` as a collabors entry for `kahlan/kahlan` (i.e. the repo).

Previously `maintainer` had `write` permissions for `kahlan/kahlan` and I just switched as `admin`. Feel free to join the #kahlan IRC channel to sort that up if it still doesn't work.
